services:
  traveltales-backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  traveltales-frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
    depends_on:
      - traveltales-backend